"""Drift check for the generated editor-facing stub `siva/spec_api.py`.

`siva/spec_api.py` is generated by `scripts/gen_spec_api.py` from the DSL
surface `siva.dsl._make_namespace` / `siva.sandbox._builder_callables`
expose. These tests fail CI the moment the checked-in file falls out of sync
with that surface -- either because someone hand-edited the generated file,
or because a DSL verb was added/removed/renamed in `siva/dsl.py` without
regenerating.

No rendering here, so this runs under a plain `.venv/bin/python -m pytest`
(no xvfb needed).
"""

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_API_PATH = REPO_ROOT / "siva" / "spec_api.py"
GEN_SCRIPT_PATH = REPO_ROOT / "scripts" / "gen_spec_api.py"


def _load_generator():
    """Import scripts/gen_spec_api.py as a module (it's not a package)."""
    spec = importlib.util.spec_from_file_location("gen_spec_api", GEN_SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_spec_api_matches_generator_output():
    """The checked-in file is byte-identical to a fresh regeneration."""
    gen = _load_generator()
    expected = gen.generate()
    actual = SPEC_API_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "siva/spec_api.py is out of sync with its generator. Regenerate with:\n"
        "    python scripts/gen_spec_api.py"
    )


def test_spec_api_all_matches_dsl_surface():
    """`__all__` covers exactly the DSL verbs the sandbox exposes, plus NodeRef/math."""
    from siva.dsl import PipelineBuilder, _make_namespace
    from siva.sandbox import _builder_callables

    builder = PipelineBuilder()
    namespace = _make_namespace(builder)
    dsl_verbs = set(_builder_callables(namespace))

    sys.path.insert(0, str(REPO_ROOT))
    import siva.spec_api as spec_api

    all_names = set(spec_api.__all__)
    assert len(spec_api.__all__) == len(all_names), "duplicate entries in __all__"

    extras = all_names - dsl_verbs
    assert extras == {"NodeRef", "math"}, (
        f"__all__ has unexpected non-verb entries: {extras - {'NodeRef', 'math'}}"
    )
    verbs_in_all = all_names - {"NodeRef", "math"}
    assert verbs_in_all == dsl_verbs, (
        f"__all__ verbs out of sync with the DSL surface.\n"
        f"Missing from __all__: {dsl_verbs - verbs_in_all}\n"
        f"Extra in __all__ (not a DSL verb): {verbs_in_all - dsl_verbs}"
    )


def test_spec_api_importable_without_vtk():
    """The stub module must not drag in vtk -- it has to stay editor-cheap."""
    sys.path.insert(0, str(REPO_ROOT))
    # Import fresh in a subprocess-free way: just check vtk isn't already
    # loaded as a side effect of importing spec_api in this process. Other
    # tests may have already imported vtk, so this only asserts something
    # meaningful when run in isolation; the real guarantee is structural
    # (spec_api.py has no siva.dsl / vtk import), checked by inspecting the
    # generator's own no-vtk-import claim below.
    import siva.spec_api  # noqa: F401
    source = SPEC_API_PATH.read_text(encoding="utf-8")
    assert "import vtk" not in source
    assert "from .dsl" not in source
    assert "from siva.dsl" not in source
