"""Drift + sync checks for the generated editor-facing stubs.

`siva/spec_api.py` and its typing foundation `siva/_spec_api_props.py` are
generated by `scripts/gen_spec_api.py` from the DSL surface
(`siva.dsl._make_namespace` / `siva.sandbox._builder_callables`) and from VTK
class introspection. These tests fail CI the moment a checked-in file falls out
of sync with that surface -- either because someone hand-edited a generated
file, or because a DSL verb / whitelisted VTK class changed without
regenerating.

These import vtk (the sync tests introspect VTK setters), so run under
`xvfb-run` like the rest of the suite; the drift comparison itself needs no
rendering.
"""

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_API_PATH = REPO_ROOT / "siva" / "spec_api.py"
SPEC_PROPS_PATH = REPO_ROOT / "siva" / "_spec_api_props.py"
GEN_SCRIPT_PATH = REPO_ROOT / "scripts" / "gen_spec_api.py"


def _load_generator():
    """Import scripts/gen_spec_api.py as a module (it's not a package)."""
    spec = importlib.util.spec_from_file_location("gen_spec_api", GEN_SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_generated_files_match_generator_output():
    """Each checked-in generated file is byte-identical to a fresh regeneration."""
    gen = _load_generator()
    for path, expected in gen.outputs().items():
        actual = path.read_text(encoding="utf-8")
        assert actual == expected, (
            f"{path.relative_to(REPO_ROOT)} is out of sync with its generator. "
            f"Regenerate with:\n    python scripts/gen_spec_api.py"
        )


def test_spec_api_all_matches_dsl_surface():
    """`__all__` covers exactly the DSL verbs the sandbox exposes, plus NodeRef/math."""
    from siva.dsl import PipelineBuilder, _make_namespace
    from siva.sandbox import _builder_callables

    builder = PipelineBuilder()
    namespace = _make_namespace(builder)
    dsl_verbs = set(_builder_callables(namespace))

    sys.path.insert(0, str(REPO_ROOT))
    import siva.spec_api as spec_api

    all_names = set(spec_api.__all__)
    assert len(spec_api.__all__) == len(all_names), "duplicate entries in __all__"

    extras = all_names - dsl_verbs
    assert extras == {"NodeRef", "math"}, (
        f"__all__ has unexpected non-verb entries: {extras - {'NodeRef', 'math'}}"
    )
    verbs_in_all = all_names - {"NodeRef", "math"}
    assert verbs_in_all == dsl_verbs, (
        f"__all__ verbs out of sync with the DSL surface.\n"
        f"Missing from __all__: {dsl_verbs - verbs_in_all}\n"
        f"Extra in __all__ (not a DSL verb): {verbs_in_all - dsl_verbs}"
    )


def test_generated_files_importable_without_vtk():
    """The stubs must not drag in vtk -- they have to stay editor-cheap."""
    sys.path.insert(0, str(REPO_ROOT))
    import siva._spec_api_props  # noqa: F401
    import siva.spec_api  # noqa: F401

    for path in (SPEC_API_PATH, SPEC_PROPS_PATH):
        source = path.read_text(encoding="utf-8")
        assert "import vtk" not in source
        assert "from .dsl" not in source
        assert "from siva.dsl" not in source


def test_props_typeddicts_cover_whitelist():
    """Every whitelisted VTK class has a TypedDict whose keys are all valid.

    The keys must be a subset of the runtime validator's own view of the
    class's setters (`vtk_setter_names`) plus the documented SIVA extras --
    i.e. the static mirror never claims a property the runtime would reject.
    """
    from siva import _spec_api_props as props
    from siva._vtk_introspect import vtk_setter_names
    from siva.filters import WHITELISTED_CLASSES

    gen = _load_generator()

    for name, cls in WHITELISTED_CLASSES.items():
        typename = gen._props_typename(name)
        assert hasattr(props, typename), f"missing TypedDict {typename} for {name}"
        td = getattr(props, typename)
        keys = set(td.__annotations__)
        allowed = vtk_setter_names(cls) | set(gen.SIVA_FILTER_EXTRAS.get(name, {}))
        stray = keys - allowed
        assert not stray, (
            f"{typename} has keys not in the runtime setter surface (or extras) "
            f"for {name}: {sorted(stray)}"
        )


def test_source_filter_overloads_cover_whitelist():
    """Every whitelisted class is reachable through a source() or filter() overload."""
    from siva.filters import WHITELISTED_CLASSES

    gen = _load_generator()
    api_source = SPEC_API_PATH.read_text(encoding="utf-8")

    for name in WHITELISTED_CLASSES:
        overload = f'"{name}"], input' if not _is_source(gen, name) else f'"{name}"], **props'
        assert overload in api_source, (
            f"{name} is missing its source()/filter() overload in spec_api.py"
        )


def _is_source(gen, name):
    from siva.filters import WHITELISTED_CLASSES

    return WHITELISTED_CLASSES[name]().GetNumberOfInputPorts() == 0
