# GENERATED FILE -- DO NOT EDIT.
#
# Generated by scripts/gen_spec_api.py from the SIVA DSL surface (VTK class introspection + siva.colormaps).
# Regenerate with:
#
#     python scripts/gen_spec_api.py

"""Typing foundation for the editor-facing SIVA spec stub.

Companion to ``siva/spec_api.py`` (which star-imports this module): it holds the
opaque :class:`NodeRef` handle, the closed-enum ``Literal`` aliases, and one
``TypedDict`` per whitelisted VTK class enumerating that class's settable
``**props``. Each TypedDict is discovered exactly the way the runtime validator
discovers valid kwargs (``siva._vtk_introspect.vtk_setter_names``), plus the
SIVA-level extras layered on by ``siva.filters`` / the DSL wrapper verbs.

Nothing here executes and nothing imports vtk -- this is pure type surface.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Literal, TypedDict

__all__ = [
    'NodeRef',
    'BackgroundPreset',
    'ColormapName',
    'Representation',
    'ScalarTypeName',
    'VtkAppendFilterProps',
    'VtkAppendPolyDataProps',
    'VtkArrayCalculatorProps',
    'VtkArrowSourceProps',
    'VtkBooleanOperationPolyDataFilterProps',
    'VtkButterflySubdivisionFilterProps',
    'VtkCellDataToPointDataProps',
    'VtkCellDerivativesProps',
    'VtkCleanPolyDataProps',
    'VtkClipDataSetProps',
    'VtkClipPolyDataProps',
    'VtkConeSourceProps',
    'VtkConnectivityFilterProps',
    'VtkContourFilterProps',
    'VtkCubeSourceProps',
    'VtkCutterProps',
    'VtkCylinderSourceProps',
    'VtkDataSetSurfaceFilterProps',
    'VtkDecimateProProps',
    'VtkDelaunay2DProps',
    'VtkDelaunay3DProps',
    'VtkDiskSourceProps',
    'VtkElevationFilterProps',
    'VtkExtractCellsProps',
    'VtkExtractEdgesProps',
    'VtkExtractGeometryProps',
    'VtkExtractGridProps',
    'VtkExtractVOIProps',
    'VtkFeatureEdgesProps',
    'VtkFillHolesFilterProps',
    'VtkFlyingEdges3DProps',
    'VtkFrustumSourceProps',
    'VtkGaussianSplatterProps',
    'VtkGenericDataObjectReaderProps',
    'VtkGeometryFilterProps',
    'VtkGlyph3DProps',
    'VtkGradientFilterProps',
    'VtkHullProps',
    'VtkImageCastProps',
    'VtkImageClipProps',
    'VtkImageExtractComponentsProps',
    'VtkImageFlipProps',
    'VtkImageGaussianSmoothProps',
    'VtkImageGradientProps',
    'VtkImageGradientMagnitudeProps',
    'VtkImageMathematicsProps',
    'VtkImageMedian3DProps',
    'VtkImageNormalizeProps',
    'VtkImageReader2Props',
    'VtkImageResampleProps',
    'VtkImageResliceProps',
    'VtkImageShiftScaleProps',
    'VtkImplicitModellerProps',
    'VtkIntersectionPolyDataFilterProps',
    'VtkLineSourceProps',
    'VtkLinearSubdivisionFilterProps',
    'VtkLoopSubdivisionFilterProps',
    'VtkMarchingCubesProps',
    'VtkMaskPointsProps',
    'VtkMassPropertiesProps',
    'VtkNrrdReaderProps',
    'VtkOBJReaderProps',
    'VtkOutlineFilterProps',
    'VtkOutlineSourceProps',
    'VtkPLYReaderProps',
    'VtkParametricFunctionSourceProps',
    'VtkPassArraysProps',
    'VtkPlaneSourceProps',
    'VtkPointDataToCellDataProps',
    'VtkPointInterpolatorProps',
    'VtkPointSourceProps',
    'VtkPoissonDiskSamplerProps',
    'VtkPolyDataConnectivityFilterProps',
    'VtkPolyDataNormalsProps',
    'VtkProbeFilterProps',
    'VtkProjectSphereFilterProps',
    'VtkQuadricDecimationProps',
    'VtkRadiusOutlierRemovalProps',
    'VtkRandomAttributeGeneratorProps',
    'VtkRectilinearGridGeometryFilterProps',
    'VtkRectilinearGridToTetrahedraProps',
    'VtkRegularPolygonSourceProps',
    'VtkResampleToImageProps',
    'VtkResampleWithDataSetProps',
    'VtkReverseSenseProps',
    'VtkRibbonFilterProps',
    'VtkSPHInterpolatorProps',
    'VtkSTLReaderProps',
    'VtkSampleImplicitFunctionFilterProps',
    'VtkSelectEnclosedPointsProps',
    'VtkShrinkFilterProps',
    'VtkShrinkPolyDataProps',
    'VtkSmoothPolyDataFilterProps',
    'VtkSphereSourceProps',
    'VtkStatisticalOutlierRemovalProps',
    'VtkStreamTracerProps',
    'VtkStripperProps',
    'VtkStructuredGridGeometryFilterProps',
    'VtkSuperquadricSourceProps',
    'VtkTableBasedClipDataSetProps',
    'VtkTableToPolyDataProps',
    'VtkTessellatedBoxSourceProps',
    'VtkTexturedSphereSourceProps',
    'VtkThresholdProps',
    'VtkThresholdPointsProps',
    'VtkTransformFilterProps',
    'VtkTransformPolyDataFilterProps',
    'VtkTriangleFilterProps',
    'VtkTubeFilterProps',
    'VtkVertexGlyphFilterProps',
    'VtkVoxelGridProps',
    'VtkWarpScalarProps',
    'VtkWarpVectorProps',
    'VtkWindowedSincPolyDataFilterProps',
    'VtkXMLImageDataReaderProps',
    'VtkXMLPolyDataReaderProps',
    'VtkXMLRectilinearGridReaderProps',
    'VtkXMLStructuredGridReaderProps',
    'VtkXMLUnstructuredGridReaderProps',
]


class NodeRef:
    """Opaque handle to a pipeline node.

    Returned by DSL forms that build pipeline nodes (``source()``,
    ``filter()``, ``contour()``, ...) and passed as ``input=`` (or another
    node-typed argument) to downstream forms. It has no usable attributes or
    methods here -- this stub only stands in for type-checking; the real
    value the sandbox holds per node is an opaque id (see
    ``siva.sandbox.NodeHandle``), and the real construction-time value is
    ``siva.dsl.NodeRef``, which never leaves the host process.
    """

    ...


# Closed-enum aliases (colormaps, scalar types, background presets, representations).
BackgroundPreset = Literal['black', 'dark', 'light', 'white']
ColormapName = Literal['blue_to_red', 'cool_to_warm', 'fire', 'grayscale', 'heat', 'oxygen', 'terrain', 'wind']
Representation = Literal['Points', 'Surface', 'Volume', 'Wireframe']
ScalarTypeName = Literal['char', 'double', 'float', 'int', 'short', 'unsigned_char', 'unsigned_int', 'unsigned_short']


class VtkAppendFilterProps(TypedDict, total=False):
    InputData: Any
    MergePoints: int
    Output: Any
    OutputPointsPrecision: int
    Tolerance: float
    ToleranceIsAbsolute: bool


class VtkAppendPolyDataProps(TypedDict, total=False):
    InputConnectionByNumber: Any
    InputData: Any
    InputDataByNumber: Any
    NumberOfInputs: int
    Output: Any
    OutputPointsPrecision: int
    ParallelStreaming: int
    UserManagedInputs: int


class VtkArrayCalculatorProps(TypedDict, total=False):
    AddScalarArrayName: Sequence[str]
    AddVectorArrayName: Sequence[str]
    AttributeType: int
    CoordinateResults: int
    Function: str
    FunctionParserType: Any
    IgnoreMissingArrays: bool
    InputData: Any
    ReplaceInvalidValues: int
    ReplacementValue: float
    ResultArrayName: str
    ResultArrayType: int
    ResultNormals: bool
    ResultTCoords: bool


class VtkArrowSourceProps(TypedDict, total=False):
    ArrowOrigin: Any
    InputData: Any
    Invert: bool
    Output: Any
    ShaftRadius: float
    ShaftResolution: int
    TipLength: float
    TipRadius: float
    TipResolution: int


class VtkBooleanOperationPolyDataFilterProps(TypedDict, total=False):
    InputData: Any
    Operation: int
    Output: Any
    ReorientDifferenceCells: int
    Tolerance: float


class VtkButterflySubdivisionFilterProps(TypedDict, total=False):
    CheckForTriangles: int
    InputData: Any
    NumberOfSubdivisions: int
    Output: Any


class VtkCellDataToPointDataProps(TypedDict, total=False):
    ContributingCellOption: int
    InputData: Any
    PassCellData: bool
    PieceInvariant: bool
    ProcessAllArrays: bool


class VtkCellDerivativesProps(TypedDict, total=False):
    InputData: Any
    TensorMode: int
    VectorMode: int


class VtkCleanPolyDataProps(TypedDict, total=False):
    AbsoluteTolerance: float
    ConvertLinesToPoints: int
    ConvertPolysToLines: int
    ConvertStripsToPolys: int
    InputData: Any
    Locator: Any
    Output: Any
    OutputPointsPrecision: int
    PieceInvariant: int
    PointMerging: int
    Tolerance: float
    ToleranceIsAbsolute: int


class VtkClipDataSetProps(TypedDict, total=False):
    ClipFunction: Any
    GenerateClipScalars: int
    GenerateClippedOutput: int
    InputData: Any
    InsideOut: int
    Locator: Any
    MergeTolerance: float
    Output: Any
    OutputPointsPrecision: int
    StableClipNonLinear: bool
    UseValueAsOffset: bool
    Value: float


class VtkClipPolyDataProps(TypedDict, total=False):
    ClipFunction: Any
    GenerateClipScalars: int
    GenerateClippedOutput: int
    InputData: Any
    InsideOut: int
    Locator: Any
    Output: Any
    OutputPointsPrecision: int
    Value: float


class VtkConeSourceProps(TypedDict, total=False):
    Angle: float
    Capping: int
    Center: Sequence[float]
    Direction: Sequence[float]
    Height: float
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    Radius: float
    Resolution: int


class VtkConnectivityFilterProps(TypedDict, total=False):
    ClosestPoint: Sequence[float]
    ColorRegions: int
    CompressArrays: bool
    ExtractionMode: int
    InputData: Any
    OutputPointsPrecision: int
    RegionIdAssignmentMode: int
    ScalarConnectivity: int
    ScalarRange: Sequence[float]


class VtkContourFilterProps(TypedDict, total=False):
    ArrayComponent: int
    ComputeGradients: int
    ComputeNormals: int
    ComputeScalars: int
    ContourBy: str
    ContourValues: Any
    FastMode: bool
    GenerateTriangles: int
    InputArray: str
    InputData: Any
    Isosurfaces: float | Sequence[float]
    Locator: Any
    NumberOfContours: int
    Output: Any
    OutputPointsPrecision: int
    ScalarTree: Any
    UseScalarTree: int
    Value: Sequence[float]


class VtkCubeSourceProps(TypedDict, total=False):
    Bounds: Any
    Center: Sequence[float]
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    XLength: float
    YLength: float
    ZLength: float


class VtkCutterProps(TypedDict, total=False):
    CutFunction: dict[str, Any]
    GenerateCutScalars: int
    GenerateTriangles: int
    InputData: Any
    Locator: Any
    NumberOfContours: int
    Output: Any
    OutputPointsPrecision: int
    SortBy: int
    Value: Sequence[float]


class VtkCylinderSourceProps(TypedDict, total=False):
    Capping: int
    CapsuleCap: int
    Center: Sequence[float]
    Height: float
    InputData: Any
    LatLongTessellation: int
    Output: Any
    OutputPointsPrecision: int
    Radius: float
    Resolution: int


class VtkDataSetSurfaceFilterProps(TypedDict, total=False):
    AllowInterpolation: int
    Delegation: int
    FastMode: bool
    InputData: Any
    MatchBoundariesIgnoringCellOrder: int
    NonlinearSubdivisionLevel: int
    OriginalCellIdsName: str
    OriginalPointIdsName: str
    Output: Any
    PassThroughCellIds: int
    PassThroughPointIds: int
    PieceInvariant: int


class VtkDecimateProProps(TypedDict, total=False):
    AbsoluteError: float
    AccumulateError: int
    BoundaryVertexDeletion: int
    Degree: int
    ErrorIsAbsolute: int
    FeatureAngle: float
    InflectionPointRatio: float
    InputData: Any
    MaximumError: float
    Output: Any
    OutputPointsPrecision: int
    PreSplitMesh: int
    PreserveTopology: int
    SplitAngle: float
    Splitting: int
    TargetReduction: float


class VtkDelaunay2DProps(TypedDict, total=False):
    Alpha: float
    BoundingTriangulation: int
    InputData: Any
    Offset: float
    Output: Any
    ProjectionPlaneMode: int
    RandomPointInsertion: int
    SourceConnection: Any
    SourceData: Any
    Tolerance: float
    Transform: Any


class VtkDelaunay3DProps(TypedDict, total=False):
    Alpha: float
    AlphaLines: int
    AlphaTets: int
    AlphaTris: int
    AlphaVerts: int
    BoundingTriangulation: int
    InputData: Any
    Locator: Any
    Offset: float
    Output: Any
    OutputPointsPrecision: int
    Tolerance: float


class VtkDiskSourceProps(TypedDict, total=False):
    Center: Sequence[float]
    CircumferentialResolution: int
    InnerRadius: float
    InputData: Any
    Normal: Sequence[float]
    OuterRadius: float
    Output: Any
    OutputPointsPrecision: int
    RadialResolution: int


class VtkElevationFilterProps(TypedDict, total=False):
    HighPoint: Sequence[float]
    InputData: Any
    LowPoint: Sequence[float]
    ScalarRange: Sequence[float]


class VtkExtractCellsProps(TypedDict, total=False):
    AssumeSortedAndUniqueIds: bool
    BatchSize: int
    CellIds: Any
    CellList: Any
    ExtractAllCells: bool
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    PassThroughCellIds: bool


class VtkExtractEdgesProps(TypedDict, total=False):
    InputData: Any
    Locator: Any
    Output: Any
    UseAllPoints: bool


class VtkExtractGeometryProps(TypedDict, total=False):
    ExtractBoundaryCells: int
    ExtractInside: int
    ExtractOnlyBoundaryCells: int
    ImplicitFunction: Any
    InputData: Any
    Output: Any


class VtkExtractGridProps(TypedDict, total=False):
    Bounds: Sequence[float]
    IncludeBoundary: int
    InputData: Any
    Output: Any
    SampleRate: Sequence[int]
    VOI: Sequence[int]


class VtkExtractVOIProps(TypedDict, total=False):
    Bounds: Sequence[float]
    IncludeBoundary: int
    InputData: Any
    Output: Any
    SampleRate: Sequence[int]
    VOI: Sequence[int]


class VtkFeatureEdgesProps(TypedDict, total=False):
    BoundaryEdges: bool
    Coloring: bool
    FeatureAngle: float
    FeatureEdges: bool
    InputData: Any
    Locator: Any
    ManifoldEdges: bool
    NonManifoldEdges: bool
    Output: Any
    OutputPointsPrecision: int
    PassLines: bool
    RemoveGhostInterfaces: bool


class VtkFillHolesFilterProps(TypedDict, total=False):
    HoleSize: float
    InputData: Any
    Output: Any


class VtkFlyingEdges3DProps(TypedDict, total=False):
    ArrayComponent: int
    ComputeGradients: int
    ComputeNormals: int
    ComputeScalars: int
    InputData: Any
    InterpolateAttributes: int
    NumberOfContours: int
    Output: Any
    Value: Sequence[float]


class VtkFrustumSourceProps(TypedDict, total=False):
    InputData: Any
    LinesLength: float
    Output: Any
    OutputPointsPrecision: int
    Planes: Any
    ShowLines: bool


class VtkGaussianSplatterProps(TypedDict, total=False):
    AccumulationMode: int
    CapValue: float
    Capping: int
    Eccentricity: float
    ExponentFactor: float
    InputData: Any
    ModelBounds: Any
    NormalWarping: int
    NullValue: float
    Output: Any
    Radius: float
    SampleDimensions: Any
    Scalar: Any
    ScalarWarping: int
    ScaleFactor: float


class VtkGenericDataObjectReaderProps(TypedDict, total=False):
    BinaryInputString: Any
    FieldDataName: str
    FileName: str
    InputArray: Any
    InputString: Any
    LookupTableName: str
    NormalsName: str
    ReadAllColorScalars: int
    ReadAllFields: int
    ReadAllNormals: int
    ReadAllScalars: int
    ReadAllTCoords: int
    ReadAllTensors: int
    ReadAllVectors: int
    ReadFromInputString: int
    ScalarsName: str
    TCoordsName: str
    TensorsName: str
    VectorsName: str


class VtkGeometryFilterProps(TypedDict, total=False):
    CellClipping: bool
    CellMaximum: int
    CellMinimum: int
    Delegation: int
    ExcludedFacesConnection: Any
    ExcludedFacesData: Any
    Extent: Any
    ExtentClipping: bool
    FastMode: bool
    InputData: Any
    MatchBoundariesIgnoringCellOrder: int
    Merging: bool
    NonlinearSubdivisionLevel: int
    OriginalCellIdsName: str
    OriginalPointIdsName: str
    Output: Any
    OutputPointsPrecision: int
    PassThroughCellIds: int
    PassThroughPointIds: int
    PieceInvariant: int
    PointClipping: bool
    PointMaximum: int
    PointMinimum: int
    RemoveGhostInterfaces: bool


class VtkGlyph3DProps(TypedDict, total=False):
    Clamping: int
    ColorMode: int
    FillCellData: int
    FollowedCameraPosition: Any
    FollowedCameraViewUp: Any
    GeneratePointIds: int
    GlyphMode: Literal["AllPoints", "EveryNthPoint", "UniformSpatialDistribution"]
    GlyphSource: NodeRef
    IndexMode: int
    InputData: Any
    Orient: int
    OrientationArray: str
    Output: Any
    OutputPointsPrecision: int
    PointIdsName: str
    Range: Sequence[float]
    ScaleArray: str
    ScaleFactor: float
    ScaleMode: int
    Scaling: int
    SourceConnection: Any
    SourceData: Any
    SourceTransform: Any
    VectorMode: Literal['FollowCameraDirection', 'UseNormal', 'UseVector', 'VectorRotationOff']


class VtkGradientFilterProps(TypedDict, total=False):
    ComputeDivergence: int
    ComputeGradient: int
    ComputeQCriterion: int
    ComputeVorticity: int
    ContributingCellOption: int
    DivergenceArrayName: str
    FasterApproximation: int
    GradientField: str
    InputData: Any
    InputScalars: Any
    QCriterionArrayName: str
    ReplacementValueOption: int
    ResultArrayName: str
    VorticityArrayName: str


class VtkHullProps(TypedDict, total=False):
    InputData: Any
    Plane: Any
    Planes: Any


class VtkImageCastProps(TypedDict, total=False):
    ClampOverflow: int
    DesiredBytesPerPiece: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    OutputScalarType: int
    SplitMode: int


class VtkImageClipProps(TypedDict, total=False):
    ClipData: int
    InputData: Any
    Output: Any
    OutputWholeExtent: Any


class VtkImageExtractComponentsProps(TypedDict, total=False):
    Components: Sequence[int]
    DesiredBytesPerPiece: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    SplitMode: int


class VtkImageFlipProps(TypedDict, total=False):
    AutoCropOutput: int
    BackgroundColor: Any
    BackgroundLevel: float
    Border: int
    BorderThickness: float
    DesiredBytesPerPiece: int
    EnableSMP: bool
    FilteredAxes: int
    FilteredAxis: int
    FlipAboutOrigin: int
    GenerateStencilOutput: int
    GlobalDefaultEnableSMP: bool
    InformationInput: Any
    InputData: Any
    Interpolate: int
    InterpolationMode: int
    Interpolator: Any
    MinimumPieceSize: Sequence[int]
    Mirror: int
    NumberOfThreads: int
    Optimization: int
    Output: Any
    OutputDimensionality: int
    OutputDirection: Any
    OutputExtent: Sequence[int]
    OutputOrigin: Sequence[float]
    OutputScalarType: int
    OutputSpacing: Sequence[float]
    PreserveImageExtent: int
    ResliceAxes: Any
    ResliceAxesDirectionCosines: Any
    ResliceAxesOrigin: Sequence[float]
    ResliceTransform: Any
    ScalarScale: float
    ScalarShift: float
    SlabMode: int
    SlabNumberOfSlices: int
    SlabSliceSpacingFraction: float
    SlabTrapezoidIntegration: int
    SplitMode: int
    StencilData: Any
    StencilOutput: Any
    TransformInputSampling: int
    Wrap: int


class VtkImageGaussianSmoothProps(TypedDict, total=False):
    DesiredBytesPerPiece: int
    Dimensionality: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    RadiusFactor: float
    RadiusFactors: Sequence[float]
    SplitMode: int
    StandardDeviation: Sequence[float]
    StandardDeviations: Sequence[float]


class VtkImageGradientProps(TypedDict, total=False):
    DesiredBytesPerPiece: int
    Dimensionality: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    HandleBoundaries: int
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    SplitMode: int


class VtkImageGradientMagnitudeProps(TypedDict, total=False):
    DesiredBytesPerPiece: int
    Dimensionality: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    HandleBoundaries: int
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    SplitMode: int


class VtkImageMathematicsProps(TypedDict, total=False):
    ConstantC: float
    ConstantK: float
    DesiredBytesPerPiece: int
    DivideByZeroToC: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    Input1Data: Any
    Input2Data: Any
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Operation: int
    Output: Any
    SplitMode: int


class VtkImageMedian3DProps(TypedDict, total=False):
    DesiredBytesPerPiece: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    InputData: Any
    KernelSize: Sequence[int]
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    SplitMode: int


class VtkImageNormalizeProps(TypedDict, total=False):
    DesiredBytesPerPiece: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    SplitMode: int


class VtkImageReader2Props(TypedDict, total=False):
    DataByteOrder: int
    DataDirection: Any
    DataExtent: Sequence[int]
    DataOrigin: Sequence[float]
    DataScalarType: ScalarTypeName | int
    DataSpacing: Sequence[float]
    FileDimensionality: int
    FileLowerLeft: int
    FileName: str
    FileNameSliceOffset: int
    FileNameSliceSpacing: int
    FileNames: Any
    FilePattern: str
    FilePrefix: str
    HeaderSize: int
    InputData: Any
    MemoryBuffer: Any
    MemoryBufferLength: int
    NumberOfScalarComponents: int
    Output: Any
    Stream: Any
    SwapBytes: int


class VtkImageResampleProps(TypedDict, total=False):
    AutoCropOutput: int
    AxisMagnificationFactor: Sequence[float]
    AxisOutputSpacing: Sequence[float]
    BackgroundColor: Any
    BackgroundLevel: float
    Border: int
    BorderThickness: float
    DesiredBytesPerPiece: int
    Dimensionality: int
    EnableSMP: bool
    GenerateStencilOutput: int
    GlobalDefaultEnableSMP: bool
    InformationInput: Any
    InputData: Any
    Interpolate: int
    InterpolationMode: int
    Interpolator: Any
    MagnificationFactors: Sequence[float]
    MinimumPieceSize: Sequence[int]
    Mirror: int
    NumberOfThreads: int
    Optimization: int
    Output: Any
    OutputDimensionality: int
    OutputDirection: Any
    OutputExtent: Sequence[int]
    OutputOrigin: Sequence[float]
    OutputScalarType: int
    OutputSpacing: Sequence[float]
    ResliceAxes: Any
    ResliceAxesDirectionCosines: Any
    ResliceAxesOrigin: Sequence[float]
    ResliceTransform: Any
    ScalarScale: float
    ScalarShift: float
    SlabMode: int
    SlabNumberOfSlices: int
    SlabSliceSpacingFraction: float
    SlabTrapezoidIntegration: int
    SplitMode: int
    StencilData: Any
    StencilOutput: Any
    TransformInputSampling: int
    Wrap: int


class VtkImageResliceProps(TypedDict, total=False):
    AutoCropOutput: int
    BackgroundColor: Any
    BackgroundLevel: float
    Border: int
    BorderThickness: float
    DesiredBytesPerPiece: int
    EnableSMP: bool
    GenerateStencilOutput: int
    GlobalDefaultEnableSMP: bool
    InformationInput: Any
    InputData: Any
    Interpolate: int
    InterpolationMode: int
    Interpolator: Any
    MinimumPieceSize: Sequence[int]
    Mirror: int
    NumberOfThreads: int
    Optimization: int
    Output: Any
    OutputDimensionality: int
    OutputDirection: Any
    OutputExtent: Sequence[int]
    OutputOrigin: Sequence[float]
    OutputScalarType: int
    OutputSpacing: Sequence[float]
    ResliceAxes: Any
    ResliceAxesDirectionCosines: Any
    ResliceAxesOrigin: Sequence[float]
    ResliceTransform: Any
    ScalarScale: float
    ScalarShift: float
    SlabMode: int
    SlabNumberOfSlices: int
    SlabSliceSpacingFraction: float
    SlabTrapezoidIntegration: int
    SplitMode: int
    StencilData: Any
    StencilOutput: Any
    TransformInputSampling: int
    Wrap: int


class VtkImageShiftScaleProps(TypedDict, total=False):
    ClampOverflow: int
    DesiredBytesPerPiece: int
    EnableSMP: bool
    GlobalDefaultEnableSMP: bool
    InputData: Any
    MinimumPieceSize: Sequence[int]
    NumberOfThreads: int
    Output: Any
    OutputScalarType: int
    Scale: float
    Shift: float
    SplitMode: int


class VtkImplicitModellerProps(TypedDict, total=False):
    AdjustBounds: int
    AdjustDistance: float
    CapValue: float
    Capping: int
    InputData: Any
    LocatorMaxLevel: int
    MaximumDistance: float
    ModelBounds: Any
    NumberOfThreads: int
    Output: Any
    OutputScalarType: int
    ProcessMode: int
    SampleDimensions: Any
    ScaleToMaximumDistance: int


class VtkIntersectionPolyDataFilterProps(TypedDict, total=False):
    CheckInput: int
    CheckMesh: int
    ComputeIntersectionPointArray: int
    InputData: Any
    Output: Any
    RelativeSubtriangleArea: float
    SplitFirstOutput: int
    SplitSecondOutput: int
    Tolerance: float


class VtkLineSourceProps(TypedDict, total=False):
    InputData: Any
    NumberOfRefinementRatios: int
    Output: Any
    OutputPointsPrecision: int
    Point1: Sequence[float]
    Point2: Sequence[float]
    Points: Any
    RefinementRatio: Sequence[float]
    Resolution: int
    UseRegularRefinement: bool


class VtkLinearSubdivisionFilterProps(TypedDict, total=False):
    CheckForTriangles: int
    InputData: Any
    NumberOfSubdivisions: int
    Output: Any


class VtkLoopSubdivisionFilterProps(TypedDict, total=False):
    CheckForTriangles: int
    InputData: Any
    NumberOfSubdivisions: int
    Output: Any


class VtkMarchingCubesProps(TypedDict, total=False):
    ComputeGradients: int
    ComputeNormals: int
    ComputeScalars: int
    InputData: Any
    Locator: Any
    NumberOfContours: int
    Output: Any
    Value: Sequence[float]


class VtkMaskPointsProps(TypedDict, total=False):
    GenerateVertices: bool
    InputData: Any
    MaximumNumberOfPoints: int
    Offset: int
    OnRatio: int
    Output: Any
    OutputPointsPrecision: int
    ProportionalMaximumNumberOfPoints: bool
    RandomMode: bool
    RandomModeType: int
    RandomSeed: int
    SingleVertexPerCell: bool


class VtkMassPropertiesProps(TypedDict, total=False):
    InputData: Any
    Output: Any


class VtkNrrdReaderProps(TypedDict, total=False):
    DataByteOrder: int
    DataDirection: Any
    DataExtent: Sequence[int]
    DataMask: int
    DataOrigin: Sequence[float]
    DataScalarType: int
    DataSpacing: Sequence[float]
    DataVOI: Sequence[int]
    FileDimensionality: int
    FileLowerLeft: int
    FileName: str
    FileNameSliceOffset: int
    FileNameSliceSpacing: int
    FileNames: Any
    FilePattern: str
    FilePrefix: str
    HeaderSize: int
    InputData: Any
    MemoryBuffer: Any
    MemoryBufferLength: int
    NumberOfScalarComponents: int
    Output: Any
    ScalarArrayName: str
    Stream: Any
    SwapBytes: int
    Transform: Any


class VtkOBJReaderProps(TypedDict, total=False):
    FileName: str
    InputData: Any
    Output: Any
    Stream: Any


class VtkOutlineFilterProps(TypedDict, total=False):
    CompositeStyle: int
    GenerateFaces: int
    InputData: Any
    Output: Any
    OutputPointsPrecision: int


class VtkOutlineSourceProps(TypedDict, total=False):
    Bounds: Any
    BoxType: int
    Corners: Any
    GenerateFaces: int
    InputData: Any
    Output: Any
    OutputPointsPrecision: int


class VtkPLYReaderProps(TypedDict, total=False):
    DuplicatePointsForFaceTexture: bool
    FaceTextureTolerance: float
    FileName: str
    InputData: Any
    InputString: str
    Output: Any
    ReadFromInputStream: bool
    ReadFromInputString: bool
    Stream: Any


class VtkParametricFunctionSourceProps(TypedDict, total=False):
    GenerateNormals: int
    GenerateTextureCoordinates: int
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    ParametricFunction: Any
    ScalarMode: int
    UResolution: int
    VResolution: int
    WResolution: int


class VtkPassArraysProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    RemoveArrays: bool
    UseFieldTypes: bool


class VtkPlaneSourceProps(TypedDict, total=False):
    Center: Any
    InputData: Any
    Normal: Any
    Origin: Sequence[float]
    Output: Any
    OutputPointsPrecision: int
    Point1: Any
    Point2: Any
    Resolution: Sequence[int]
    XResolution: int
    YResolution: int


class VtkPointDataToCellDataProps(TypedDict, total=False):
    CategoricalData: bool
    InputData: Any
    PassPointData: bool
    ProcessAllArrays: bool


class VtkPointInterpolatorProps(TypedDict, total=False):
    InputData: Any
    Kernel: Any
    Locator: Any
    NullPointsStrategy: int
    NullValue: float
    PassCellArrays: bool
    PassFieldArrays: bool
    PassPointArrays: bool
    PromoteOutputArrays: bool
    SourceConnection: Any
    SourceData: Any
    ValidPointsMaskArrayName: str


class VtkPointSourceProps(TypedDict, total=False):
    Center: Sequence[float]
    Distribution: int
    InputData: Any
    Lambda: float
    NumberOfPoints: int
    Output: Any
    OutputPointsPrecision: int
    Radius: float
    RandomSequence: Any


class VtkPoissonDiskSamplerProps(TypedDict, total=False):
    InputData: Any
    Locator: Any
    Radius: float


class VtkPolyDataConnectivityFilterProps(TypedDict, total=False):
    ClosestPoint: Sequence[float]
    ColorRegions: int
    ExtractionMode: int
    FullScalarConnectivity: int
    InputData: Any
    MarkVisitedPointIds: int
    Output: Any
    OutputPointsPrecision: int
    ScalarConnectivity: int
    ScalarRange: Sequence[float]


class VtkPolyDataNormalsProps(TypedDict, total=False):
    AutoOrientNormals: int
    ComputeCellNormals: int
    ComputePointNormals: int
    Consistency: int
    FeatureAngle: float
    FlipNormals: int
    InputData: Any
    NonManifoldTraversal: int
    Output: Any
    OutputPointsPrecision: int
    Splitting: int


class VtkProbeFilterProps(TypedDict, total=False):
    CategoricalData: int
    CellLocatorPrototype: Any
    ComputeTolerance: bool
    FindCellStrategy: Any
    InputData: Any
    PassCellArrays: int
    PassFieldArrays: int
    PassPointArrays: int
    SnapToCellWithClosestPoint: bool
    SourceConnection: Any
    SourceData: Any
    SpatialMatch: int
    Tolerance: float
    ValidPointMaskArrayName: str


class VtkProjectSphereFilterProps(TypedDict, total=False):
    Center: Sequence[float]
    InputData: Any
    KeepPolePoints: bool
    TranslateZ: bool


class VtkQuadricDecimationProps(TypedDict, total=False):
    AttributeErrorMetric: int
    BoundaryWeightFactor: float
    InputData: Any
    MapPointData: bool
    MaximumError: float
    NormalsAttribute: int
    NormalsWeight: float
    Output: Any
    Regularization: float
    Regularize: int
    ScalarsAttribute: int
    ScalarsWeight: float
    TCoordsAttribute: int
    TCoordsWeight: float
    TargetReduction: float
    TensorsAttribute: int
    TensorsWeight: float
    VectorsAttribute: int
    VectorsWeight: float
    VolumePreservation: int
    WeighBoundaryConstraintsByLength: int


class VtkRadiusOutlierRemovalProps(TypedDict, total=False):
    GenerateOutliers: bool
    GenerateVertices: bool
    InputData: Any
    Locator: Any
    NumberOfNeighbors: int
    Output: Any
    Radius: float


class VtkRandomAttributeGeneratorProps(TypedDict, total=False):
    AttributesConstantPerBlock: bool
    ComponentRange: Any
    DataType: int
    GenerateCellArray: int
    GenerateCellNormals: int
    GenerateCellScalars: int
    GenerateCellTCoords: int
    GenerateCellTensors: int
    GenerateCellVectors: int
    GenerateFieldArray: int
    GeneratePointArray: int
    GeneratePointNormals: int
    GeneratePointScalars: int
    GeneratePointTCoords: int
    GeneratePointTensors: int
    GeneratePointVectors: int
    InputData: Any
    MaximumComponentValue: float
    MinimumComponentValue: float
    NumberOfComponents: int
    NumberOfTuples: int


class VtkRectilinearGridGeometryFilterProps(TypedDict, total=False):
    Extent: Any
    InputData: Any
    Output: Any


class VtkRectilinearGridToTetrahedraProps(TypedDict, total=False):
    Input: Any
    InputData: Any
    Output: Any
    RememberVoxelId: int
    TetraPerCell: int


class VtkRegularPolygonSourceProps(TypedDict, total=False):
    Center: Sequence[float]
    GeneratePolygon: int
    GeneratePolyline: int
    InputData: Any
    Normal: Sequence[float]
    NumberOfSides: int
    Output: Any
    OutputPointsPrecision: int
    Radius: float


class VtkResampleToImageProps(TypedDict, total=False):
    Controller: Any
    SamplingBounds: Any
    SamplingDimensions: Sequence[int]
    UseInputBounds: bool


class VtkResampleWithDataSetProps(TypedDict, total=False):
    CategoricalData: bool
    CellLocatorPrototype: Any
    ComputeTolerance: bool
    Controller: Any
    InputData: Any
    MarkBlankPointsAndCells: bool
    PassCellArrays: bool
    PassFieldArrays: bool
    PassPartialArrays: bool
    PassPointArrays: bool
    SnapToCellWithClosestPoint: bool
    SourceConnection: Any
    SourceData: Any
    Tolerance: float
    UseBalancedPartitionForPointsLookup: bool
    UseImplicitArrays: bool


class VtkReverseSenseProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    ReverseCells: int
    ReverseNormals: int


class VtkRibbonFilterProps(TypedDict, total=False):
    Angle: float
    DefaultNormal: Sequence[float]
    GenerateTCoords: int
    InputData: Any
    Output: Any
    TextureLength: float
    UseDefaultNormal: int
    VaryWidth: int
    Width: float
    WidthFactor: float


class VtkSPHInterpolatorProps(TypedDict, total=False):
    ComputeShepardSum: int
    CutoffArrayName: str
    DensityArrayName: str
    InputData: Any
    Kernel: Any
    Locator: Any
    MassArrayName: str
    NullPointsStrategy: int
    NullValue: float
    PassCellArrays: int
    PassFieldArrays: int
    PassPointArrays: int
    PromoteOutputArrays: int
    ShepardNormalization: int
    ShepardSumArrayName: str
    SourceConnection: Any
    SourceData: Any
    ValidPointsMaskArrayName: str


class VtkSTLReaderProps(TypedDict, total=False):
    FileName: str
    InputData: Any
    Locator: Any
    Merging: int
    Output: Any
    RelaxedConformance: bool
    ScalarTags: int
    Stream: Any


class VtkSampleImplicitFunctionFilterProps(TypedDict, total=False):
    ComputeGradients: int
    GradientArrayName: str
    ImplicitFunction: Any
    InputData: Any
    ScalarArrayName: str


class VtkSelectEnclosedPointsProps(TypedDict, total=False):
    CheckSurface: int
    InputData: Any
    InsideOut: int
    SurfaceConnection: Any
    SurfaceData: Any
    Tolerance: float


class VtkShrinkFilterProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    ShrinkFactor: float


class VtkShrinkPolyDataProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    ShrinkFactor: float


class VtkSmoothPolyDataFilterProps(TypedDict, total=False):
    BoundarySmoothing: int
    Convergence: float
    EdgeAngle: float
    FeatureAngle: float
    FeatureEdgeSmoothing: int
    GenerateErrorScalars: int
    GenerateErrorVectors: int
    InputData: Any
    NumberOfIterations: int
    Output: Any
    OutputPointsPrecision: int
    RelaxationFactor: float
    SourceData: Any


class VtkSphereSourceProps(TypedDict, total=False):
    Center: Sequence[float]
    EndPhi: float
    EndTheta: float
    GenerateNormals: int
    InputData: Any
    LatLongTessellation: int
    Output: Any
    OutputPointsPrecision: int
    PhiResolution: int
    Radius: float
    StartPhi: float
    StartTheta: float
    ThetaResolution: int


class VtkStatisticalOutlierRemovalProps(TypedDict, total=False):
    ComputedMean: float
    ComputedStandardDeviation: float
    GenerateOutliers: bool
    GenerateVertices: bool
    InputData: Any
    Locator: Any
    Output: Any
    SampleSize: int
    StandardDeviationFactor: float


class VtkStreamTracerProps(TypedDict, total=False):
    ComputeVorticity: bool
    ForceSerialExecution: bool
    InitialIntegrationStep: float
    InputData: Any
    IntegrationDirection: Literal["Forward", "Backward", "Both"]
    IntegrationStepUnit: int
    Integrator: Any
    IntegratorType: Literal["RungeKutta2", "RungeKutta4", "RungeKutta45"]
    InterpolatorPrototype: Any
    InterpolatorType: int
    MaximumError: float
    MaximumIntegrationStep: float
    MaximumNumberOfSteps: int
    MaximumPropagation: float
    MinimumIntegrationStep: float
    Output: Any
    RotationScale: float
    SeedSource: NodeRef
    SourceConnection: Any
    SourceData: Any
    StartPosition: Sequence[float]
    SurfaceStreamlines: bool
    TerminalSpeed: float
    UseLocalSeedSource: bool
    Vectors: str


class VtkStripperProps(TypedDict, total=False):
    InputData: Any
    JoinContiguousSegments: int
    MaximumLength: int
    Output: Any
    PassCellDataAsFieldData: int
    PassThroughCellIds: int
    PassThroughPointIds: int


class VtkStructuredGridGeometryFilterProps(TypedDict, total=False):
    Extent: Any
    InputData: Any
    Output: Any


class VtkSuperquadricSourceProps(TypedDict, total=False):
    AxisOfSymmetry: int
    Center: Sequence[float]
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    PhiResolution: int
    PhiRoundness: float
    Scale: Sequence[float]
    Size: float
    ThetaResolution: int
    ThetaRoundness: float
    Thickness: float
    Toroidal: int


class VtkTableBasedClipDataSetProps(TypedDict, total=False):
    BatchSize: int
    ClipFunction: Any
    GenerateClipPointTypes: bool
    GenerateClipScalars: int
    GenerateClippedOutput: int
    InputData: Any
    InsideOut: int
    Locator: Any
    MergeTolerance: float
    Output: Any
    OutputPointsPrecision: int
    UseValueAsOffset: bool
    Value: float


class VtkTableToPolyDataProps(TypedDict, total=False):
    Create2DPoints: bool
    InputData: Any
    Output: Any
    PreserveCoordinateColumnsAsDataArrays: bool
    XColumn: str
    XColumnIndex: int
    XComponent: int
    YColumn: str
    YColumnIndex: int
    YComponent: int
    ZColumn: str
    ZColumnIndex: int
    ZComponent: int


class VtkTessellatedBoxSourceProps(TypedDict, total=False):
    Bounds: Any
    DuplicateSharedPoints: int
    InputData: Any
    Level: int
    Output: Any
    OutputPointsPrecision: int
    Quads: int


class VtkTexturedSphereSourceProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    Phi: float
    PhiResolution: int
    Radius: float
    Theta: float
    ThetaResolution: int


class VtkThresholdProps(TypedDict, total=False):
    AllScalars: int
    ComponentMode: int
    InputData: Any
    Invert: bool
    LowerThreshold: float
    Output: Any
    OutputPointsPrecision: int
    SelectedComponent: int
    ThresholdBy: str
    ThresholdFunction: int
    ThresholdRange: Sequence[float]
    UpperThreshold: float
    UseContinuousCellRange: int


class VtkThresholdPointsProps(TypedDict, total=False):
    InputArrayComponent: int
    InputData: Any
    LowerThreshold: float
    Output: Any
    OutputPointsPrecision: int
    ThresholdFunction: int
    UpperThreshold: float


class VtkTransformFilterProps(TypedDict, total=False):
    InputData: Any
    OutputPointsPrecision: int
    Transform: Any
    TransformAllInputVectors: bool


class VtkTransformPolyDataFilterProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    OutputPointsPrecision: int
    Transform: Any


class VtkTriangleFilterProps(TypedDict, total=False):
    InputData: Any
    Output: Any
    PassLines: int
    PassVerts: int
    PreservePolys: int
    Tolerance: float


class VtkTubeFilterProps(TypedDict, total=False):
    Capping: int
    DefaultNormal: Sequence[float]
    GenerateTCoords: int
    InputData: Any
    NumberOfSides: int
    Offset: int
    OnRatio: int
    Output: Any
    OutputPointsPrecision: int
    Radius: float
    RadiusFactor: float
    SidesShareVertices: int
    TextureLength: float
    UseDefaultNormal: int
    VaryRadius: int


class VtkVertexGlyphFilterProps(TypedDict, total=False):
    InputData: Any
    Output: Any


class VtkVoxelGridProps(TypedDict, total=False):
    ConfigurationStyle: int
    Divisions: Sequence[int]
    InputData: Any
    Kernel: Any
    LeafSize: Sequence[float]
    NumberOfPointsPerBin: int
    Output: Any


class VtkWarpScalarProps(TypedDict, total=False):
    GenerateEnclosure: bool
    InputData: Any
    Normal: Sequence[float]
    OutputPointsPrecision: int
    ScaleFactor: float
    UseNormal: int
    Vectors: str
    XYPlane: int


class VtkWarpVectorProps(TypedDict, total=False):
    InputData: Any
    OutputPointsPrecision: int
    ScaleFactor: float
    Vectors: str


class VtkWindowedSincPolyDataFilterProps(TypedDict, total=False):
    BoundarySmoothing: int
    EdgeAngle: float
    FeatureAngle: float
    FeatureEdgeSmoothing: int
    GenerateErrorScalars: int
    GenerateErrorVectors: int
    InputData: Any
    NonManifoldSmoothing: int
    NormalizeCoordinates: int
    NumberOfIterations: int
    Output: Any
    PassBand: float
    WeightNonManifoldEdges: int
    WindowFunction: int


class VtkXMLImageDataReaderProps(TypedDict, total=False):
    ActiveTimeDataArrayName: str
    BinaryInputString: Any
    CellArrayStatus: Any
    ColumnArrayStatus: Any
    FileName: str
    InputArray: Any
    InputString: Any
    ParserErrorObserver: Any
    PointArrayStatus: Any
    ReadFromInputString: int
    ReaderErrorObserver: Any
    TimeStep: int
    TimeStepRange: Sequence[int]
    WholeSlices: int


class VtkXMLPolyDataReaderProps(TypedDict, total=False):
    ActiveTimeDataArrayName: str
    BinaryInputString: Any
    CellArrayStatus: Any
    ColumnArrayStatus: Any
    FileName: str
    InputArray: Any
    InputString: Any
    ParserErrorObserver: Any
    PointArrayStatus: Any
    ReadFromInputString: int
    ReaderErrorObserver: Any
    TimeStep: int
    TimeStepRange: Sequence[int]
    upUpdateExtent: Any


class VtkXMLRectilinearGridReaderProps(TypedDict, total=False):
    ActiveTimeDataArrayName: str
    BinaryInputString: Any
    CellArrayStatus: Any
    ColumnArrayStatus: Any
    FileName: str
    InputArray: Any
    InputString: Any
    ParserErrorObserver: Any
    PointArrayStatus: Any
    ReadFromInputString: int
    ReaderErrorObserver: Any
    TimeStep: int
    TimeStepRange: Sequence[int]
    WholeSlices: int


class VtkXMLStructuredGridReaderProps(TypedDict, total=False):
    ActiveTimeDataArrayName: str
    BinaryInputString: Any
    CellArrayStatus: Any
    ColumnArrayStatus: Any
    FileName: str
    InputArray: Any
    InputString: Any
    ParserErrorObserver: Any
    PointArrayStatus: Any
    ReadFromInputString: int
    ReaderErrorObserver: Any
    TimeStep: int
    TimeStepRange: Sequence[int]
    WholeSlices: int


class VtkXMLUnstructuredGridReaderProps(TypedDict, total=False):
    ActiveTimeDataArrayName: str
    BinaryInputString: Any
    CellArrayStatus: Any
    ColumnArrayStatus: Any
    FileName: str
    InputArray: Any
    InputString: Any
    ParserErrorObserver: Any
    PointArrayStatus: Any
    ReadFromInputString: int
    ReaderErrorObserver: Any
    TimeStep: int
    TimeStepRange: Sequence[int]
    upUpdateExtent: Any
